name: Continuous version release to npm

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - website/**
      - coverage/**

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, 'feat') || contains(github.event.head_commit.message, 'fix') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: update package version
        if: ${{ contains(github.event.head_commit.message, 'feat') || contains(github.event.head_commit.message, 'fix') }}
        run: |
          npm version prerelease --preid=beta --ignore-scripts
          git push origin ${{ github.ref_name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          
