name: Sync

on:
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GH_PUSH_TOKEN }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                owner: 'kwasniew',
                repo: 'source',
                workflow_id: 'continuous_version_sync.yml',
                ref: 'main'
              })

